export enum ENotificationType {
  COMMENT = 'COMMENT',
  ISSUE_UPDATED = 'ISSUE_UPDATED',
  DOC_CHANGED = 'DOC_CHANGED',
  TASK_CHANGED = 'TASK_CHANGED',
  REQ_CHANGED = 'REQ_CHANGED',
  API_CHANGED = 'API_CHANGED',
  INVITED = 'INVITED',
}
