export enum EWidgetType {
  PROJ_PRGS = 'PROJ_PRGS',
  REQ_IMPL_STAT = 'REQ_IMPL_STAT',
  API_IMPL_STAT = 'API_IMPL_STAT',
  ISSUE_TASK_STAT = 'ISSUE_TASK_STAT',
  ACTIVE_FEED = 'ACTIVE_FEED',
  TEST_STAT = 'TEST_STAT',
  IMPACT_ANALY = 'IMPACT_ANALY',
}
