name: PR Management
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml

  auto_assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.2
        with:
          configuration-path: .github/auto-assign.yaml
