name: PR Management
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml

  auto_assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: shufo/auto-assign-reviewer-by-files@v1.2.1
        with:
          config: .github/auto-assign.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
